### ISSUE TITLE
[Add Webradio]: Radio Paradise (320k)

### ISSUE THREAD

**Issue by wernersz72** [jcorporation/webradiodb#222] opened 2022-03-28 08:52 UTC
### Webradio Name

Radio Paradise (320k)

### Stream URI

http://stream-uk1.radioparadise.com/aac-320

### Genres

california, eclectic, free, internet, non-commercial, paradise, radio

### Homepage

https://www.radioparadise.com/

### Image

https://www.radioparadise.com/favicon.ico

### Country

The United States Of America

### Language

english

**Comment by jcorporation** [comment] 2022-03-28 09:13
Duplicate of https://github.com/jcorporation/webradiodb/blob/master/docs/db/webradios/https___stream_radioparadise_com_aac-320.m3u

**Closed by jcorporation** 2022-03-28 09:13 UTC
Labels: AddWebradio, Duplicate
